version: "3"
services:
  monapp:
    build: .
    image: first-im
    depends_on:
      - redis
    ports:
      - "82:82"
    networks:
      - monreseau
    environment:
      - NOM=Ahmed CHOUCHEN
  redis:
    image: redis
    networks:
      - monreseau
networks:
  monreseau:
